In [182]:
from PIL import Image, ImageOps
import numpy as np
import copy
i1 = Image.open('Images\cleared_cube.png')
ancho, alto = i1.size
print(f'{ancho}, {alto}')

657, 487


In [197]:
class cube:
    """
    Clase cubo que contiene 6 objetos _cube_face que corresponden a las caras del cubo.
    """
    class _cube_face:
        """
        Clase representativa de la cara de un cubo que contiene 9 celdas.
        """

        def __init__(self):
            """
            Constructor de la cara, con 1 array bidimensional 3x3 y 4 atributos usados para referenciar las caras vecinas.

            Attributes:
                matrix (numpy.ndarray)
                up (Nonetype): Vecino encima.
                down (Nonetype): Vecino debajo.
                left (Nonetype): Vecino a la izquierda.
                right (Nonetype): Vecino a la derecha.
            """
            self.matrix = np.zeros((3, 3))
            self.up = None
            self.down = None
            self.left = None
            self.right = None

        def links(self, up, down, left, right):
            """
            Función que enlaza las caras vecinas de una respectiva cara.

            Args:
                up (_cube_face): Vecino encima.
                down (_cube_face): Vecino debajo.
                left (_cube_face): Vecino a la izquierda.
                right (_cube_face): Vecino a la derecha.

            Attributes:
                up (_cube_face): Vecino encima.
                down (_cube_face): Vecino debajo.
                left (_cube_face): Vecino a la izquierda.
                right (_cube_face): Vecino a la derecha.
            """
            self.up = up
            self.down = down
            self.left = left
            self.right = right

        def clockwise(self):
            """
            Rotación a favor del reloj a partir de una cara.
            """
            # Rotación de la matrix de la cara.
            self.matrix = np.rot90(self.matrix, axes=(1, 0))

            # Rotación de las celdas afectadas de los vecinos.
            temp = copy.copy(self.right.matrix[:,0][::-1]) # copy.copy es para evitar se asigne una referencia. El valor es invertido.
            self.right.matrix[:,[0]] = np.array([self.up.matrix[2]]).T
            self.up.matrix[2] = self.left.matrix[:,2][::-1] # El valor es invertido.
            self.left.matrix[:,[2]] = np.array([self.down.matrix[0]]).T
            self.down.matrix[0] = temp

        def anticlockwise(self):
            """Rotación contrarreloj a partir de una cara"""
            try:
                self.matrix = np.rot90(self.matrix, axes=(0, 1))
            except:
                print('Error')

    def __init__(self):
        """
        Constructor del cubo, genera las 6 caras y las enlaza con sus respectivas vecinas.

        Attributes:
            F (_cube_face): Cara frontal (front).
            R (_cube_face): Cara derecha (right).
            B (_cube_face): Cara trasera (back).
            L (_cube_face): Cara izquierda (left).
            U (_cube_face): Cara superior (up).
            D (_cube_face): Cara inferior (down).
        """
        self.F = self._cube_face()
        self.R = self._cube_face()
        self.B = self._cube_face()
        self.L = self._cube_face()
        self.U = self._cube_face()
        self.D = self._cube_face()
        
        self.F.links(self.U, self.D, self.L, self.R)
        self.R.links(self.U, self.D, self.F, self.B)
        self.B.links(self.U, self.D, self.R, self.L)
        self.L.links(self.U, self.D, self.B, self.F)
        self.U.links(self.B, self.F, self.R, self.L)
        self.D.links(self.F, self.B, self.R, self.L)

In [198]:
a = cube()
a.F.matrix = np.array([[j+1+3*i for j in range(len(a.U.matrix))] for i in range(len(a.U.matrix))], dtype = np.float32)
a.U.matrix = np.array([[j+1+3*i for j in range(len(a.U.matrix))] for i in range(len(a.U.matrix))], dtype = np.float32)
# print(a.F.matrix)

print('----------')
print(a.U.matrix)
print(a.R.matrix)
print(a.D.matrix)
print(a.L.matrix)
a.F.clockwise()
print('----------')
print(a.U.matrix)
print(a.R.matrix)
print(a.D.matrix)
print(a.L.matrix)
a.F.clockwise()
print('----------')
print(a.U.matrix)
print(a.R.matrix)
print(a.D.matrix)
print(a.L.matrix)
a.F.clockwise()
print('----------')
print(a.U.matrix)
print(a.R.matrix)
print(a.D.matrix)
print(a.L.matrix)
a.F.clockwise()
print('----------')
print(a.U.matrix)
print(a.R.matrix)
print(a.D.matrix)
print(a.L.matrix)

----------
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------
[[1. 2. 3.]
 [4. 5. 6.]
 [0. 0. 0.]]
[[7. 0. 0.]
 [8. 0. 0.]
 [9. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------
[[1. 2. 3.]
 [4. 5. 6.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[9. 8. 7.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------
[[1. 2. 3.]
 [4. 5. 6.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 9.]
 [0. 0. 8.]
 [0. 0. 7.]]
----------
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
